"""Update event fields

Revision ID: 41e2d63bc478
Revises: 9b6f39060a25
Create Date: 2026-02-26 07:31:44.244750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e2d63bc478'
down_revision = '9b6f39060a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))
        batch_op.alter_column('event_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('ticket_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('latitude')
        batch_op.drop_column('name')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.alter_column('ticket_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('event_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('location')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
