"""Update email to be unique

Revision ID: 9b6f39060a25
Revises: 626d07b28b19
Create Date: 2025-09-10 10:52:45.425082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6f39060a25'
down_revision = '626d07b28b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'email',
            existing_type=sa.VARCHAR(),
            nullable=False
        )
        batch_op.create_unique_constraint('uq_users_email', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.alter_column(
            'email',
            existing_type=sa.VARCHAR(),
            nullable=True
        )
    # ### end Alembic commands ###
