"""Add payment tables: triggers, payments and webhooks

Revision ID: c2f9dc4a1dea
Revises: bf7685118b40
Create Date: 2026-03-16 15:42:45.247188

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2f9dc4a1dea"
down_revision = "bf7685118b40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_tracking_id", sa.String(length=100), nullable=True),
        sa.Column("merchant_reference", sa.String(length=50), nullable=True),
        sa.Column("order_notification_type", sa.String(length=20), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("order_tracking_id", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("payment_account", sa.String(length=120), nullable=True),
        sa.Column("confirmation_code", sa.String(length=120), nullable=True),
        sa.Column("payment_status_description", sa.String(length=20), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("callback_url", sa.Text(), nullable=True),
        sa.Column("payment_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "triggers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("notification_id", sa.String(length=100), nullable=False),
        sa.Column("order_tracking_id", sa.String(length=100), nullable=True),
        sa.Column("redirect_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id"),
    )
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False)
        )
        batch_op.add_column(sa.Column("status", sa.String(length=20), nullable=False))
        batch_op.add_column(
            sa.Column("full_name", sa.String(length=100), nullable=False)
        )
        batch_op.add_column(sa.Column("email", sa.String(length=100), nullable=False))
        batch_op.add_column(
            sa.Column("phone_number", sa.String(length=20), nullable=False)
        )
        batch_op.drop_column("tickets_quantity")
        batch_op.drop_column("event_price")
        batch_op.drop_column("user_id")
        batch_op.drop_column("checked_in_Date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("checked_in_Date", sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(
            sa.Column("event_price", sa.NUMERIC(precision=10, scale=2), nullable=True)
        )
        batch_op.add_column(sa.Column("tickets_quantity", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])
        batch_op.drop_column("phone_number")
        batch_op.drop_column("email")
        batch_op.drop_column("full_name")
        batch_op.drop_column("status")
        batch_op.drop_column("total_amount")

    op.drop_table("triggers")
    op.drop_table("payments")
    op.drop_table("webhooks")
    # ### end Alembic commands ###
